dist: trusty
language: java
jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: "danielmkraus"

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify org.jacoco:jacoco-maven-plugin:report -P coverage-per-test
  - mvn sonar:sonar -P coverage-per-test

cache:
  directories:
    - $HOME/.m2

deploy:
  provider: releases
  api_key: "1502820b019c5bd8befdaace469394c29b46c2fc"
  file: "./target/transfer-service*.jar"
  skip_cleanup: true
  on:
    tags: true