dist: trusty
language: java
jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: "danielmkraus"

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:0.8.5:prepare-agent verify -P coverage-per-test
  - mvn sonar:sonar -P coverage-per-test

cache:
  directories:
    - $HOME/.m2
